# Generated by Django 4.0.3 on 2022-03-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='cmc_id',
            field=models.IntegerField(null=True),
        ),
    ]
