# Generated by Django 4.0.2 on 2022-03-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_crypto_cmc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='crypto',
            field=models.ManyToManyField(through='main_app.Amount', to='main_app.Crypto'),
        ),
    ]
